# Generated by Django 4.1.7 on 2023-04-24 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_alter_house_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='oblast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='blogs.oblast'),
        ),
        migrations.AlterField(
            model_name='oblast',
            name='owner',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='oblasts', to=settings.AUTH_USER_MODEL),
        ),
    ]
