# Generated by Django 4.2 on 2023-04-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_add_city_to_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oblast',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='house',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='house',
            name='street',
        ),
        migrations.AddField(
            model_name='blog',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.city'),
        ),
        migrations.AddField(
            model_name='blog',
            name='house',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='blogs.house'),
        ),
        migrations.AddField(
            model_name='blog',
            name='oblast',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='blogs.oblast'),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.city'),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.house'),
        ),
    ]
