# Generated by Django 4.2 on 2023-04-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_options_alter_city_options_and_more'),
    ]

    operations = [
    ]
